frontend/urls.py
from django.urls import path, re_path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

app_name = 'frontend'

urlpatterns = [
    re_path(r'.*$', login_required(TemplateView.as_view(template_name='frontend/index.html')), name='index'),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
  path('super/todo/', views.TodoListView.as_view(), name='todo-list'),
  path('super/todo/<int:pk>', views.TodoDetailView.as_view(), name='todo-detail'),
  path('todo/', views.UserTodoListView.as_view(), name='todo-list'),
  path('todo/<int:pk>', views.UserTodoDetailView.as_view(), name='todo-detail'),
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('todo.urls')),
    path('auth/', include('userauth.urls')),
    path('', include('frontend.urls')),
]

userauth/urls.py
from django.urls import path, re_path, reverse_lazy, reverse
from django.views.generic import TemplateView
from django.contrib.auth import views as AuthViews
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'userauth'

urlpatterns = [
  path('login/', views.LoginView.as_view(), name='login'),
  path('logout/', views.LogoutView.as_view(next_page=reverse_lazy('userauth:signup')), name='logout'),

  path('signup/', views.signup, name='signup'),
  path('about/',  TemplateView.as_view(template_name='userauth/about.html'), name='about'),

  re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.account_activate, name='account_activate'),
  path('activation-email-sent/', TemplateView.as_view(template_name='userauth/account_activation_sent.html'), name='account_activation_sent'),

  path('password_change/', login_required(views.PasswordChangeView.as_view()), name='password_change'),

  path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
  path('password_reset/done/', AuthViews.PasswordResetDoneView.as_view(template_name='userauth/password_reset/password_reset_done.html'), name='password_reset_done'),
  path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

  path('delete-account/', login_required(views.delete_user), name='delete_user'),
]

frontend/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Todo(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  title = models.CharField(max_length=60)
  description = models.TextField()
  deadline = models.DateTimeField()
  completed = models.BooleanField(default=False)

  def __str__(self):
    return self.title

userauth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Account(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  email_confirmed = models.BooleanField(default=False)

@receiver(post_save, sender=User)
def update_user_account(sender, instance, created, **kwargs):
  if created:
    Account.objects.create(user=instance)
  instance.account.save()

userauth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
  email = forms.EmailField(max_length=254)

  class Meta:
    model = User
    fields = ('username', 'email', 'password1', 'password2', )

frontend/views.py
from django.shortcuts import render

# Create your views here.

todo/views.py
from rest_framework import generics, viewsets
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .models import Todo
from .serializers import TodoSerializer

# Create your views here.

class SuperUserTestMixin(UserPassesTestMixin):
  def test_func(self):
    return self.request.user.is_authenticated and self.request.user.is_superuser
        
class TodoListView(SuperUserTestMixin, generics.ListCreateAPIView):
  queryset = Todo.objects.all()
  serializer_class = TodoSerializer

class TodoDetailView(SuperUserTestMixin, generics.RetrieveUpdateDestroyAPIView):
  queryset = Todo.objects.all()
  serializer_class = TodoSerializer

class UserTodoListView(LoginRequiredMixin, generics.ListCreateAPIView):
  serializer_class = TodoSerializer

  def get_queryset(self):
    return Todo.objects.filter(user=self.request.user)

class UserTodoDetailView(LoginRequiredMixin, generics.RetrieveUpdateDestroyAPIView):
  serializer_class = TodoSerializer

  def get_queryset(self):
    return Todo.objects.filter(user=self.request.user)

userauth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm
from .tokens import account_activation_token

from django.contrib.auth.views import LoginView as AuthLoginView, LogoutView, PasswordChangeView as AuthPasswordChangeView, PasswordResetView as AuthPasswordResetView, PasswordResetConfirmView as AuthPasswordResetConfirmView
from django.contrib.auth import logout
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import login
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode ,urlsafe_base64_decode
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

# Create your views here.
class LoginView(AuthLoginView):
  template_name = 'userauth/login.html'
  next = reverse_lazy('frontend:index')

class PasswordChangeView(SuccessMessageMixin, AuthPasswordChangeView):
  template_name = 'userauth/password_change.html' 
  success_url = '/'
  success_message = 'Password updated successfully.'

def signup(request):
  if request.method == 'POST':
    form = SignUpForm(request.POST)
    if form.is_valid():
      user = form.save(commit=False)
      user.is_active = False
      user.save()
      current_site = get_current_site(request)
      subject = 'Activate your TodoEPC Account.'
      message = render_to_string('userauth/account_activation_email.html',{
        'user': user,
        'protocol': request.scheme,
        'domain': request.get_host(),
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
      })
      user.email_user(subject, message)
      return redirect('userauth:account_activation_sent')

  else:
    form = SignUpForm()
    print(request.get_host())

  return render(request, 'userauth/signup.html', {'form': form})

def account_activate(request, uidb64, token):
  try:
    uid = force_text(urlsafe_base64_decode(uidb64))
    user = User.objects.get(pk=uid)
  except (TypeError, ValueError, OverflowError, User.DoesNotExist):
    user = None

  if user is not None and account_activation_token.check_token(user, token):
    user.is_active = True
    user.account.email_confirmed = True
    user.save()
    login(request, user)
    return redirect('frontend:index')
  else:
    return render(request, 'userauth/account_activation_invalid.html')

class PasswordResetView(AuthPasswordResetView):
  template_name = 'userauth/password_reset/password_reset.html'
  email_template_name = 'userauth/password_reset/password_reset_email.html'
  subject_template_name = 'userauth/password_reset/password_reset_subject.txt'
  success_url = reverse_lazy('userauth:password_reset_done')

class PasswordResetConfirmView(SuccessMessageMixin, AuthPasswordResetConfirmView):
  template_name = 'userauth/password_reset/password_reset_confirm.html'
  post_reset_login = True
  success_url = '/'
  success_message = 'Password updated successfully.'

def delete_user(request):
  user = request.user
  logout(request)
  user.delete()
  redirect('userauth:signup')

frontend/templates/frontend/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Todo List</title>
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  {% load static %}
</head>
<body>
  <div id="user_id" class="d-none" >{{ request.user.id }}</div>
  {% if messages %}
    <div id="messages" class="d-none">
      {% for message in messages %}
      <span {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</span>
      {% endfor %}
    </div>
  {% endif %}
  <div id="root"></div>
  <script src="{% static 'frontend/main.js' %}"></script>
</body>
</html>

userauth/templates/userauth/about.html
{% extends 'userauth/base.html' %}

{% block base %}
{% load static %}
<div class="row">
  <div class="col border-right border-primary bg-primary d-none d-md-block">
    {% include 'userauth/about_col.html' %}
  </div>
  <div class="col">
    <div class="mt-4 mx-4 mb-4">
      <h2 class="text-primary">About</h2>
      <hr>
      <p>TodoEPC is a simple app to keep track of your todos. You get to add, edit, mark as complete/incomplete, delete your todos. But it won't stop there. It is and will continue to evlove to make your life easier everyday.</p>
      <p>The app, in software terms, could be considered as a basic CRUD(Create-Read-Update-Delete) app. Falling under the client-server model, the client(React) makes API calls to the server(Django REST framework), fetches the todos and presents them while the server(Django REST framework) exposes API endpoints, handles the authentication, communicates with the database.</p>
      <div class="row">
        <div class="col">
          <h5>Tech Stack</h5>
          <ul>
            <li>Django REST framework</li>
            <li>ReactJS</li>
            <li>Bootstrap</li>
            <li>Axios</li>
            <li>React Toastify</li>
          </ul>
        </div>
        <div class="col">
          <h5>Concepts Implemeted</h5>
          <ul>
            <li>Django+React Integration</li>
            <li>API Implementation</li>
            <li>Session Authentication</li>
            <li>Email Verification</li>
          </ul>
        </div>
      </div>
      {% include 'userauth/auth_links.html' %}
    </div>
  </div>
</div>
{% endblock %}

userauth/templates/userauth/about_col.html
{% load static %}
<div class="my-4 mx-4">
  <h2 class="text-white">Welcome to TodoEPC</h2>
  <hr style="background-color: aliceblue;">
  <div class="row mt-5">
    <div class="col text-center">
      <img src="{% static 'userauth/plan.svg' %}" alt="Knock it off!" height="120px" class="mx-auto img-fluid">
      <h4 class="text-white mt-3">Plan your actions as todos.</h4>
    </div>
    <div class="col text-center">
      <img src="{% static 'userauth/knock.svg' %}" alt="Knock it off!" height="120px" class="mx-auto img-fluid">
      <h4 class="text-white mt-3">Knock it off one at a time.</h4>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col text-center">
      <img src="{% static 'userauth/stepup.svg' %}" alt="Knock it off!" height="120px" class="mx-auto">
      <h4 class="text-white mt-3">Step up your game.</h4>
    </div>
  </div>
  <hr style="background-color: aliceblue; border-top: 0.5px solid rgba(0, 0, 0, 0.1);">
  <p class="text-white text-center">Made with <i class="fa fa-heart text-danger"></i> ( and litte bit of <i class="fa fa-coffee"></i> ) by <a href="https://www.linkedin.com/in/eswar-clynn/" class="font-weight-bold" style="color: #63D8FF;">Eswar Clynn</a></p>
</div>

userauth/templates/userauth/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to activate your account on TodoEPC:

{{ protocol }}://{{ domain }}{% url 'userauth:account_activate' uidb64=uid token=token %}
{% endautoescape %}

userauth/templates/userauth/account_activation_invalid.html
{% extends 'userauth/auth.html' %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}
  <h2 class="text-primary">Account Activation Failed</h2>
  <hr>
  <h5>Uh oh! Seems like you followed the wrong link. <span class="text-primary">Please verify the link from your inbox!</span></h5>
  <img src="{% static 'userauth/email_sent.svg' %}" alt="Email Sent" height="300px" class="mt-5 d-block mx-auto">

  <!-- <hr style="border-top: 0.5px solid rgba(0, 0, 0, 0.1);">
  <p class="text-white text-center">Made with <i class="fa fa-heart text-danger"></i> ( and litte bit of <i class="fa fa-coffee"></i> ) by <a href="https://www.linkedin.com/in/eswar-clynn/" class="font-weight-bold" style="color: #63D8FF;">Eswar Clynn</a></p> -->
{% endblock %}

userauth/templates/userauth/account_activation_sent.html
{% extends 'userauth/auth.html' %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}
  <h2 class="text-primary">Account Activation</h2>
  <hr>
  <h5>We've sent you an email with instructions to activate your account. <span class="text-primary">Please check your inbox!</span></h5>
  <img src="{% static 'userauth/email_sent.svg' %}" alt="Email Sent" height="300px" class="mt-5 d-block mx-auto mb-5 img-fluid">
{% endblock %}

userauth/templates/userauth/auth.html
{% extends 'userauth/base.html' %}

{% block base %}
{% load static %}
<div class="row">
  <div class="col border-right border-primary bg-primary d-none d-md-block">
    {% include 'userauth/about_col.html' %}
  </div>
  <div class="col">
    <div class="mt-4 mx-4 mb-4">
      {% block content %}
      {% endblock %}
      {% include 'userauth/auth_links.html' %}
    </div>
  </div>
</div>
{% endblock %}

userauth/templates/userauth/auth_links.html
<hr style="background-color: aliceblue; border-top: 0.5px solid rgba(0, 0, 0, 0.1);">
<div class="row">
  <div class="d-flex col">
    {% if request.path == '/auth/signup/' %}
      <a href="{% url 'userauth:login' %}" class="btn btn-outline-primary">Login</a>
      <a href="{% url 'userauth:about' %}" class="btn btn-outline-dark ml-auto">About</a>
    {% endif %}

    {% if request.path == '/auth/about/' %}
      {% if request.user.is_authenticated %}
        <a href="{% url 'frontend:index' %}" class="btn btn-outline-dark">Back to app!</a>
        <a href="{% url 'userauth:password_change' %}" class="btn btn-outline-dark ml-auto">Change Password</a>
        <a href="{% url 'userauth:delete_user' %}" class="btn btn-outline-dark ml-auto" onclick="return confirm('Are you sure? We\'re sorry to see you go.😢')">Delete my account</a>
      {% else %}
        <a href="{% url 'userauth:login' %}" class="btn btn-outline-primary">Login</a>
        <a href="{% url 'userauth:signup' %}" class="btn btn-outline-primary ml-auto">Sign Up</a>
      {% endif %}
    {% endif %}

    {% if request.path == '/auth/login/' %}
      <a href="{% url 'userauth:signup' %}" class="btn btn-outline-primary">Sign Up</a>
      <a href="{% url 'userauth:password_reset' %}" class="btn btn-outline-dark ml-auto">Forgot Password?</a>
    {% endif %}

    {% if request.path == '/auth/activation-email-sent/' %}
      <a href="{% url 'userauth:login' %}" class="btn btn-outline-primary">Login</a>
      <a href="{% url 'userauth:signup' %}" class="btn btn-outline-primary ml-auto">Sign Up</a>
    {% endif %}

    {% if request.path == '/auth/password_change/' %}
      <a href="{% url 'frontend:index' %}" class="btn btn-outline-dark">Back to app!</a>
      <a href="{% url 'userauth:about' %}" class="btn btn-outline-dark ml-auto">About</a>
    {% endif %}

    {% if request.path == '/auth/password_reset/' or request.path == '/auth/password_reset/done/' or request.path == '/auth/password_reset_confirm/' %}
      <a href="{% url 'userauth:login' %}" class="btn btn-outline-primary">Login</a>
      <a href="{% url 'userauth:signup' %}" class="btn btn-outline-primary ml-2">Sign Up</a>
      <a href="{% url 'userauth:about' %}" class="btn btn-outline-dark ml-auto">About</a>
    {% endif %}
      
    
  </div>
</div>

userauth/templates/userauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Todo List</title>
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  {% load static %}
</head>
<body>
  <script src="{% static 'frontend/main.js' %}"></script>
  <div class="container main-container">
    {% block base %}
    {% endblock %}
  </div> 
</body>
</html>

userauth/templates/userauth/login.html
{% extends 'userauth/auth.html' %}

{% block content %}
{% load crispy_forms_tags %}
  <h2 class="text-primary">Log in</h2>
  <hr>
  <form method="post">
  {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mb-1">Log in</button>
  </form>
{% endblock %}

userauth/templates/userauth/password_change.html
{% extends 'userauth/auth.html' %}

{% block content %}
{% load crispy_forms_tags %}
  <h2 class="text-primary">Change Password</h2>
  <hr>
  <form method="post">
  {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mb-1">Update Password</button>
  </form>
{% endblock %}

userauth/templates/userauth/password_change_done.html
{% extends 'userauth/auth.html' %}

{% block content %}
{% load crispy_forms_tags %}
  <h2 class="text-primary">Password Changed</h2>
  <hr>
  <form method="post">
  {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mb-1">Log in</button>
  </form>
{% endblock %}

userauth/templates/userauth/password_reset/password_reset.html
{% extends 'userauth/auth.html' %}

{% block content %}
{% load crispy_forms_tags %}
  <h2 class="text-primary">Password Reset</h2>
  <hr>
  <form method="post">
  {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mb-1">Send Email</button>
  </form>
{% endblock %}

userauth/templates/userauth/password_reset/password_reset_confirm.html
{% extends 'userauth/auth.html' %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}
  {% if validlink %}
    <h2 class="text-primary">Change Password</h2>
    <hr>
    <form method="post">
    {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary mb-1">Update Password</button>
    </form>
  {% else %}
    <h2 class="text-primary">Password Reset - Invalid Link</h2>
    <hr>
    <h5>Uh oh! Seems like you followed the wrong link. <span class="text-primary">Please verify the link from your inbox!</span></h5>
    <img src="{% static 'userauth/email_sent.svg' %}" alt="Email Sent" height="300px" class="mt-5 d-block mx-auto">
  {% endif %}
    
{% endblock %}

userauth/templates/userauth/password_reset/password_reset_done.html
{% extends 'userauth/auth.html' %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}
  <h2 class="text-primary">Password Reset</h2>
  <hr>
  <h5>We've sent you an email with instructions to reset your password. <span class="text-primary">Please check your inbox!</span></h5>
  <img src="{% static 'userauth/email_sent.svg' %}" alt="Email Sent" height="300px" class="mt-5 d-block mx-auto mb-5 img-fluid">
{% endblock %}

userauth/templates/userauth/password_reset/password_reset_email.html
Hi {{ user.username }},

We've received a request for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'userauth:password_reset_confirm' uidb64=uid token=token %}

If you've not requested a password reset, please ignore this email and we'll take care of the rest.

userauth/templates/userauth/signup.html
{% extends 'userauth/auth.html' %}

{% block content %}
{% load crispy_forms_tags %}

  <style>
    #hint_id_username {
      display: none;
    }
  </style>
  <h2 class="text-primary">Sign up</h2>
  <hr>
  <form method="post" class="">
  {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mb-1">Sign up</button>
  </form>
{% endblock %}